Add `EnvironmentBuilder` and remove `Manager`
primitivefinance/arbiter pull request #518
Opened 2023-09-21 18:35 UTC by kinrezC

**Give an overview of the tasks completed**
- Remove `manager.rs`
- Add `EnvironmentBuilder` struct for easy `Environment` and `EnvironmentParameter` configuration
- `Environment` `label: String` -> `label: Option<String>`
- Refactor tests to remove `manager` 

**Link to issue(s) that this PR closes**
For #513

2023-09-21 21:04 UTC, 0xJepsen approved these changes
@kinrezC I must say, and i don't say this often, but i think think this is the right abstraction. Really awesome work on this

2023-09-21 21:15 UTC, Autoparallel requested changes
This looks super good! I love it.

I left some comments and suggestions but nothing major.

2023-09-21 21:15 UTC, Autoparallel commented on arbiter-core/src/environment.rs
> +    }
Can we do this instead?
```suggestion
    pub fn label(mut self, label: impl Into<String>) -> Self {
        self.label = Some(label.into());
        self
    }
```

2023-09-21 21:15 UTC, Autoparallel commented on arbiter-core/src/environment.rs
> +                );
Can we do:
```suggestion
                if let Some(label) {
                info!(
                    "Pausing environment with label: {}",
                    label
                );
                } else {
                info!("Pausing environment...");
                }
```

2023-09-21 21:15 UTC, Autoparallel commented on arbiter-core/src/environment.rs
> +                );
Can we do:
```suggestion
                                if let Some(label) {
                info!(
                    "Pausing environment with label: {}",
                    label
                );
                } else {
                info!("Pausing environment...");
                }
```

2023-09-21 21:15 UTC, Autoparallel commented on arbiter-core/src/environment.rs
> +    #[default]
This is a new trick for me!

2023-09-21 21:15 UTC, Autoparallel commented on arbiter-core/src/environment.rs
> +            .label(TEST_ENV_LABEL.into())
with other change you can drop `.into()` here.

2023-09-21 21:15 UTC, Autoparallel commented on arbiter-core/src/environment.rs
> +            .label(TEST_ENV_LABEL.into())
And everywhere else.

2023-09-22 18:00 UTC, Alexangelj reviewed
I only did a high level overview of the changes - overall this is a much better dev experience, after experiencing how to figure out how to get all the default values I need to initialize the environment, it's nice its all handled for me

2023-09-23 04:09 UTC, merged