Event Logger
primitivefinance/arbiter pull request #561
Opened 2023-10-02 17:33 UTC by kinrezC

**Give an overview of the tasks completed**
Introduces `EventLogger`.  `EventLogger` has an `EventLoggerBuilder` which allows one to chain `EventLogger::builder().add(contract0.events()).add(contract1.events())` to listen for events on specified contracts.  When the `EventLogger` is `run().await` it will watch for events and write them to a csv.  

**Link to issue(s) that this PR closes**
For #515

2023-10-02 17:48 UTC, 0xJepsen approved these changes
This is so clean @kinrezC! Awesome work on this! You are officially the async rust chad.

2023-10-02 21:46 UTC, Autoparallel requested changes
How is the stop signal sent to the data collector? Do we need that ever? Can you explain why/why not?

2023-10-02 21:46 UTC, Autoparallel commented on arbiter-core/src/tests/data_output.rs
My comments are mostly here.

Can we perhaps have these tests check that the files are actually created and have the correct data in them?

We don't need to take it super far, but I feel like these don't check all that much other than that this runs.

2023-10-03 18:08 UTC, Alexangelj approved these changes
Looks excellent

2023-10-03 18:22 UTC, merged