Feature/forking eoa
primitivefinance/arbiter pull request #620
Opened 2023-10-16 23:46 UTC by 0xJepsen

Add support to the fork CLI to be able to fork externally owned accounts

Closes #619

2023-10-17 18:59 UTC, Autoparallel requested changes

2023-10-17 18:59 UTC, Autoparallel commented on example_fork/weth_config.toml
> +externally_owned_accounts = ["0xd8dA6BF26964aF9D7eEd9e03E53415D37aA96045"] # vitalik.eth as of 10/2/2023
I think this should be a hashmap so we can reference by string the eoas

2023-10-18 18:57 UTC, 0xJepsen commented
The requested cahnges have been resolved and logic has been added to the test to ensure the data is being fetched from the chain, written to storage, and read into revm correctly. The one thing i realized and am not sure how to work with is that we cannot make a wallet object to a particular address without the private key. From what i know the address is a has of the public key which is generated from the private key by multiplying a generator point in the elliptic curve field. by some pseudorandom number. I was looking at the [ethers-signers](https://github.com/gakonst/ethers-rs/blob/master/ethers-signers/src/wallet/mod.rs) to see if there were any mock wallets that bypassed this in tests but didn't find anything. We kinda want to just gas light revm into verifying the signature is right. Maybe we want to change wallet struct attribute of the provide to out own for this?

2023-10-18 22:40 UTC, Autoparallel commented
> The requested cahnges have been resolved and logic has been added to the test to ensure the data is being fetched from the chain, written to storage, and read into revm correctly. The one thing i realized and am not sure how to work with is that we cannot make a wallet object to a particular address without the private key. From what i know the address is a has of the public key which is generated from the private key by multiplying a generator point in the elliptic curve field. by some pseudorandom number. I was looking at the [ethers-signers](https://github.com/gakonst/ethers-rs/blob/master/ethers-signers/src/wallet/mod.rs) to see if there were any mock wallets that bypassed this in tests but didn't find anything. We kinda want to just gas light revm into verifying the signature is right. Maybe we want to change wallet struct attribute of the provide to out own for this?

This is true. We will need a new way to create a `RevmMiddleware`. We can just do something like
```rust
fn new_from_address(env: Environment, address: Address, label: Option<&str>) -> {
...
}
```

Nothing crazy.

2023-10-18 22:41 UTC, Autoparallel approved these changes

2023-10-18 22:42 UTC, merged